export const MOCK_DOCUMENTS = [
  {
    id: 1,
    title: 'Đề án tuyển sinh đại học năm 2026',
    description: 'Thông tin chi tiết về phương thức tuyển sinh, chỉ tiêu, ngành đào tạo và các mốc thời gian quan trọng.',
    date: '09/09/2026',
    type: 'PDF',
    size: '2.4 MB',
  },
  {
    id: 2,
    title: 'Quy chế tuyển sinh đại học chính quy',
    description: 'Quy định về tuyển sinh đại học chính quy của Học viện Công nghệ Bưu chính Viễn thông.',
    date: '08/09/2026',
    type: 'DOCX',
    size: '850 KB',
  },
  {
    id: 3,
    title: 'Hướng dẫn đăng ký xét tuyển trực tuyến',
    description: 'Hướng dẫn chi tiết các bước đăng ký xét tuyển trực tuyến trên hệ thống của Học viện.',
    date: '05/09/2026',
    type: 'PDF',
    size: '1.1 MB',
  },
  {
    id: 4,
    title: 'Câu hỏi thường gặp về tuyển sinh',
    description: 'Tổng hợp các câu hỏi thường gặp và giải đáp về tuyển sinh.',
    date: '03/09/2026',
    type: 'TXT',
    size: '120 KB',
  },
  {
    id: 5,
    title: 'Quy định về học phí năm 2026',
    description: 'Thông tin chi tiết về mức học phí, các chính sách miễn giảm và hỗ trợ học phí.',
    date: '01/09/2026',
    type: 'DOCX',
    size: '760 KB',
  },
  {
    id: 6,
    title: 'Giới thiệu các ngành đào tạo',
    description: 'Thông tin tổng quan về các ngành đào tạo, chuẩn đầu ra và cơ hội nghề nghiệp.',
    date: '28/08/2026',
    type: 'PDF',
    size: '3.2 MB',
  },
  {
    id: 7,
    title: 'Thông tin học bổng dành cho tân sinh viên',
    description: 'Danh sách các chương trình học bổng, điều kiện xét và thời gian đăng ký.',
    date: '25/08/2026',
    type: 'PDF',
    size: '980 KB',
  },
  {
    id: 8,
    title: 'Lịch các mốc tuyển sinh quan trọng',
    description: 'Tổng hợp các mốc thời gian quan trọng trong kỳ tuyển sinh đại học năm 2026.',
    date: '21/08/2026',
    type: 'PDF',
    size: '640 KB',
  },
  {
    id: 9,
    title: 'Hướng dẫn nhập học trực tuyến',
    description: 'Các bước xác nhận nhập học, chuẩn bị hồ sơ và hoàn tất thủ tục trực tuyến.',
    date: '18/08/2026',
    type: 'DOCX',
    size: '1.4 MB',
  },
  {
    id: 10,
    title: 'Danh mục hồ sơ nhập học',
    description: 'Danh sách giấy tờ cần chuẩn bị khi làm thủ tục nhập học tại Học viện.',
    date: '15/08/2026',
    type: 'PDF',
    size: '530 KB',
  },
  {
    id: 11,
    title: 'Thông tin ký túc xá và hỗ trợ sinh viên',
    description: 'Thông tin về ký túc xá, các dịch vụ hỗ trợ và đầu mối liên hệ cho tân sinh viên.',
    date: '10/08/2026',
    type: 'PDF',
    size: '1.8 MB',
  },
  {
    id: 12,
    title: 'Thông tin liên hệ tuyển sinh',
    description: 'Danh sách kênh tư vấn và thông tin liên hệ của bộ phận tuyển sinh PTIT.',
    date: '05/08/2026',
    type: 'TXT',
    size: '85 KB',
  },
];

export const DOCUMENT_TYPES = ['Tất cả định dạng', 'PDF', 'DOCX', 'TXT'];
