
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${app.config.server-port}
server.servlet.context-path=${app.config.context-path}
spring.application.name=${app.config.application-name}

spring.datasource.url=${app.config.datasource-url}
spring.datasource.driverClassName=${app.config.datasource-driver}
spring.datasource.username=${app.config.datasource-username}
spring.datasource.password=${app.config.datasource-password}
spring.jpa.hibernate.ddl-auto=${app.config.jpa-ddl-auto}
spring.jpa.show-sql=${app.config.jpa-show-sql}

jwt.signerKey=${app.config.jwt-signer-key}
jwt.valid-duration=${app.config.jwt-valid-duration}
jwt.refreshable-duration=${app.config.jwt-refreshable-duration}

app.frontend-url=${app.config.frontend-url}
app.password-reset.expiration-minutes=${app.config.password-reset-expiration-minutes}

spring.mail.host=${app.config.mail-host}
spring.mail.port=${app.config.mail-port}
spring.mail.username=${app.config.mail-username}
spring.mail.password=${app.config.mail-password}
spring.mail.properties.mail.smtp.auth=${app.config.mail-smtp-auth}
spring.mail.properties.mail.smtp.starttls.enable=${app.config.mail-starttls-enable}


